### ISSUE TITLE
Make AdGuard Home addon use IPv4 and IPv6 at the same time

### ISSUE THREAD

**Issue by flozsc** [hassio-addons/addon-adguard-home#139] opened 2021-03-21 20:53 UTC
# Problem/Motivation

> I would like to use AdGuard Home in my IPv6/IPv4 mixed network.

## Expected behavior

> AdGuard Home DNS service would bind to both interfaces, the IPv4 and the IPv6 one.

## Actual behavior

> Unfortunatley, with v4.0.0 update, AdGuard Home only binds to primary interface.

## Steps to reproduce

> Have Hassio in an IPv6/IPv4 mixed setup.
> Install AdGuard Home addon.
> Check "Client Setup" page to see that AdGuard Home DNS service only bound to IPv4 interface.

## Proposed changes

> An option could be providing a setting to specify the IP addresses to bind to.

**Comment by sinclairpaul** [comment] 2021-03-21 21:08
Duplicate of #138 #134

**Closed** 2021-03-21 21:09 UTC
