### ISSUE TITLE
Migration from eth0 to end0 for DHCP

### ISSUE THREAD

**Issue by MiguelAngelLV** [hassio-addons/addon-adguard-home#461] opened 2023-10-14 05:19 UTC
# Problem/Motivation

When update Home Assistant Supervisor to 11.0, eth0 change to end0, so, Adguard select a random network device (Docker0 in my case) instead end0 and it does not work fine

## Expected behavior

After update to Supervisor 11.0, Adguard set end0 instead of eth0

## Actual behavior

Set a random network device

## Steps to reproduce

- With supervisor 10.X, configure adguard with DHCP server and eth0
- Update to supervisor 11.X

**Comment by LoermansA** [comment] 2023-10-15 17:39
I seem to be experiencing the same problem. I've had to revert to my networks default DHCP server to get everything up and running again.

**Comment by dredjohn21** [comment] 2023-10-17 02:08
I also couldn’t figure out how to solve this and had to revert to my routers dhcp

**Comment by MiguelAngelLV** [comment] 2023-10-19 16:29
> I also couldn’t figure out how to solve this and had to revert to my routers dhcp

Only need set end0 in network device:

![image](https://github.com/hassio-addons/addon-adguard-home/assets/638110/bb967e0a-dfc3-4964-9ca9-464991552ef5)

**Comment by LoermansA** [comment] 2023-10-19 18:57
> > I also couldn’t figure out how to solve this and had to revert to my routers dhcp
> 
> Only need set end0 in network device:
> 
> ![image](https://user-images.githubusercontent.com/638110/276685699-bb967e0a-dfc3-4964-9ca9-464991552ef5.png)

Oh wow, now I feel really silly! Awesome, thanks for your reply!

**Comment by sinclairpaul** [comment] 2023-10-19 21:34
I think we can close this out, it's likely caused by a breaking change in the Home Assistant OS latest release and listed in the release notes - <https://github.com/home-assistant/operating-system/releases/tag/11.0>

**Closed by sinclairpaul** 2023-10-19 21:34 UTC
