### ISSUE TITLE
Fixed IP address not recognized

### ISSUE THREAD

**Issue by wildcheese1** [hassio-addons/addon-adguard-home#89] opened 2020-11-12 08:48 UTC
# Problem/Motivation

I have set a fixed IP address in Hassio via 

- Supervisor - System - Change IP address. I've set the address I want on the LAN and provided 8.8.8.8 as DNS server. 

I want to enable the DHCP server in Adguard Home addonn .

## Expected behavior

> I expected the DHCP server to start as I do have a static IP set in Hassio.

## Actual behavior

> DHCP server didn't start. It tells me: In order to use DHCP server a static IP address must be set. We failed to determine if this network interface is configured using static IP address. Please set a static IP address manually.

## Steps to reproduce

> Set up the static IP on a clean install of Hassio

## Proposed changes

> Work around can be the USB drive or via SSH - though as my Hassio is really stable and as I'm a noob I prefer not to do to much indepth changes. The setting for a static IP via the webinterface is for me less impacting than the USB or SSH option.
> Suggested change: let Adguard detect the webpage setting, or let Adguard start the DHCP without it being sure that a static IP has been set.

**Comment by abooysen** [comment] 2020-11-12 12:30
I'm struggling with the same issue and would really like to get it working so I can implement MAC specific rules.
My Raspberry is configured with a static IP over a LAN connection.

 Add-on version: 2.6.1
 You are running the latest version of this add-on.
 System: HassOS 4.16  (armv7 / raspberrypi4)
 Home Assistant Core: 0.117.6
 Home Assistant Supervisor: 2020.11.0

**Comment by AlecRust** [comment] 2020-11-12 13:41
FWIW I also get "We failed to determine if this network interface is configured using static IP address" notice when checking for DHCP server and when enabling the AdGuard Home DHCP server, but enabling still works on the second try.

**Comment by wildcheese1** [comment] 2020-11-13 10:27
> FWIW I also get "We failed to determine if this network interface is configured using static IP address" notice when checking for DHCP server and when enabling the AdGuard Home DHCP server, but enabling still works on the second try.

Interesting - I can not even select the "enable DHCP server" - I can click on it but it doesnt 'recolor'

**Comment by abooysen** [comment] 2020-11-13 11:04
I cannot either, I even tried to remove the "disabled" in the html for the button. Then I can click it but it still does not do anything.
Possibly there is something else preventing it from working , we should possibly try posting on the Adguard forum. Is there somewhere where I can see the actual command when Hassio starts this docker container. I tried setting the Adguard log to trace but no luck in getting more information

**Comment by wildcheese1** [comment] 2020-11-15 15:31
same here, I have tried all including fixing the IP address via the CLI. I think this is more a Hassio addon issue than a Adquard home, thats why I posted my question here. But maybe you right it may be as well in the general Adguard Home forum.

**Comment by vPotusFlotus** [comment] 2020-11-17 14:09
> > FWIW I also get "We failed to determine if this network interface is configured using static IP address" notice when checking for DHCP server and when enabling the AdGuard Home DHCP server, but enabling still works on the second try.
> 
> Interesting - I can not even select the "enable DHCP server" - I can click on it but it doesnt 'recolor'

I have the same issue, although without any error message. Just can't click the 'enable DHCP server' button, DHCP config is set & saved correctly. The 'enable DHCP server' button looks clickable, but no 'recoloring' and doesn't do anything. Also set logs to debug but doesn't show much.

**Comment by AlecRust** [comment] 2020-11-20 10:46
I wonder if this is fixed in just released [AdGuard Home v0.104.3](https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.104.3). This PR seems related: https://github.com/AdguardTeam/AdGuardHome/issues/2301

**Comment by polzy** [comment] 2020-11-20 12:47
i have v0.104.1 how to force update to v0.104.3 in hassio ?

**Comment by frenck** [comment] 2020-11-20 12:47
The add-on needs an update. Unless you build your own add-on, you can't force it.

**Comment by frenck** [comment] 2020-11-20 12:53
I'm scheduling an update and release for today.

**Comment by polzy** [comment] 2020-11-22 21:26
i have update adguard to hassio and i have the same problem. 
the problem is ipv6, it’s possible to disable ipv6 in hassio ?

**Comment by LordNex** [comment] 2020-11-22 23:06
Ditto, same issue and the DHCP on my Netgear R7000P just isn't keeping up anymore. Devices keep getting private assigned addresses due to timeouts in the ack. Any update on this? Guess for now I'll use the other DHCP add on but would prefer to just run it all through this. Thanks!

**Comment by VR6Pete** [comment] 2020-11-25 13:15
Yes - Same issue here. I see that 0.104.3 has been released so would be good to see a new image get built :D

**Comment by arturasaleknavicius** [comment] 2020-12-04 22:15
Same issue here never used DHCP of addon before, but were not able to switch it on at the moment.

**Comment by colingg** [comment] 2020-12-06 19:44
Same issue here :/ have setup a fixed ip in hassio, no button to activate dhcp

**Comment by VR6Pete** [comment] 2020-12-06 20:27
Think we are just waiting for @frenck to release an update !

**Comment by KennyHGregory** [comment] 2020-12-19 03:02
Looks like changes for AdGuard Home to v0.104.3 got committed. But a release hasn't been created.

**Comment by whitelodge** [comment] 2020-12-29 10:58
I'm experiencing this issue with the 2.6.1 release.

**Comment by sparksken** [comment] 2020-12-30 00:13
Same issue on 2.6.1.

**Comment by grischard** [comment] 2020-12-31 00:00
If anyone wants to enable dhcp manually in the meantime:

```
docker exec -it addon_a0d7b954_adguard /bin/bash
vi /data/adguard/AdGuardHome.yaml
```

scroll down to `dhcp`, set `enabled: ` to `true`. Restart the container, wipe hands on trousers.

**Comment by LordNex** [comment] 2020-12-31 12:24
Can you still manage it through the web interfaces to set reservations and such? I ended up just using the dhcp add on for HA instead of AdGuard but would prefer to run it all from one container.


On Dec 30, 2020, at 6:00 PM, Guillaume Rischard <notifications@github.com> wrote:

﻿

If anyone wants to enable dhcp manually in the meantime:

docker exec -it addon_a0d7b954_adguard /bin/bash
vi /data/adguard/AdGuardHome.yaml


scroll down to dhcp, set enabled: to true. Restart the container, wipe hands on trousers.

**Comment by grischard** [comment] 2021-01-01 16:49
> Can you still manage it through the web interfaces to set reservations and such? I ended up just using the dhcp add on for HA instead of AdGuard but would prefer to run it all from one container.

Yes, adding fixed leases through AdGuard works fine for me. If it doesn't work for you, it might be because the dhcp server isn't enabled?

**Comment by Cyr-ius** [comment] 2021-01-05 07:51
@Frenck, update 0.104.3 has not been updated 
The AdGuard version of container 2.6.1 is still in 0.104.1
 Is this normal?

**Comment by frenck** [comment] 2021-01-05 07:52
Right now: yes

**Comment by tyjtyj** [comment] 2021-02-04 22:30
> 
> 
> i have update adguard to hassio and i have the same problem.
> the problem is ipv6, it’s possible to disable ipv6 in hassio ?


Its not IPV6 issue. i disable ipv6 and still not able enabled. something wrong with the image.

**Comment by Gaspard-Bourgeois** [comment] 2021-02-08 23:54
I successfully enabled the dhcp server on mine, it wasn't working with the previous version. So thank you very much !

Tolet you know it kept saying "We failed to determine if this network interface is configured using static IP address"

**Comment by RichLewis007** [comment] 2021-02-09 21:09
Yes, I agree, in this latest version the DHCP server option works whereas in the previous version it didn't.

**Comment by sinclairpaul** [comment] 2021-02-09 21:23
> So, I recommend this issue be closed. Thanks!

That's good enough reason for me 😉

**Closed by sinclairpaul** 2021-02-09 21:23 UTC
