### ISSUE TITLE
Static DHCP Leases not working and list deletes itself after every restart

### ISSUE THREAD

**Issue by gil906** [hassio-addons/addon-adguard-home#34] opened 2019-09-20 16:32 UTC
# Problem/Motivation
Static DHCP Leases not working and list deletes itself after every restart.

## Expected behavior
To Assign the assigned IP created on the Static DHCP Pool and to retain the information after every restart.

## Actual behavior
Static DHCP List deletes itself after every restart and before the restart, it doesn't work anyways.

## Steps to reproduce
Assigning Static DHCP Leases, 
When tested, not working, still gets a random IP
After restart, the Static DHCP list that was created will be blank.

**Comment by frenck** [comment] 2019-09-20 16:41
Duplicate of #33

**Closed by frenck** 2019-09-20 16:41 UTC
