### ISSUE TITLE
Adguard-Addon does not start on Odroid C2

### ISSUE THREAD

**Issue by kreisklasse** [hassio-addons/addon-adguard-home#6] opened 2019-02-08 13:37 UTC
# Problem/Motivation

> Adguard-Addon does not start on Odroid C2 (log below)
> aarch64 / HassOS 2.8 / HA 0.87.0 / SU 143 / stable

## Actual behavior

>  [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 00-banner.sh: executing... 
>  Hass.io Add-on: AdGuard Home v0.1.1
>  Network-wide ads & trackers blocking DNS server.
>  From: Community Hass.io Add-ons
>  By: Franck Nijhof <frenck@addons.community>

 

> aarch64 / HassOS 2.8 / HA 0.87.0 / SU 143 / stable
> [cont-init.d] 00-banner.sh: exited 0.
> [cont-init.d] 01-log-level.sh: executing... 
> Log level is set to INFO
> [cont-init.d] 01-log-level.sh: exited 0.
> [cont-init.d] 02-updates.sh: executing... 
> INFO: You are running the latest version of this add-on
> [cont-init.d] 02-updates.sh: exited 0.
> [cont-init.d] 10-requirements.sh: executing... 
> [cont-init.d] 10-requirements.sh: exited 0.
> [cont-init.d] 11-nginx.sh: executing... 
> [cont-init.d] 11-nginx.sh: exited 0.
> [cont-init.d] 20-config.sh: executing... 
> [cont-init.d] 20-config.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 2019/02/08 13:28:02 AdGuard Home web interface backend, version v0.92-hotfix2
> 2019/02/08 13:28:02 Current working directory is /opt/AdGuardHome
> 2019/02/08 13:28:02 main.upgradeConfig(): got schema version 2
> 2019/02/08 13:28:02 Reading YAML file: /opt/AdGuardHome/data/AdGuardHome.yaml
> 2019/02/08 13:28:02 Loading filter 1 contents to: /opt/AdGuardHome/data/filters/1.txt
> 2019/02/08 13:28:02 File /opt/AdGuardHome/data/filters/1.txt, id 1, length 507908
> 2019/02/08 13:28:02 Downloading update for filter 1 from https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> 2019/02/08 13:28:07 Filter 1 has been updated: 508024 bytes, 26406 rules
> 2019/02/08 13:28:07 Saving filter 1 contents to: /opt/AdGuardHome/data/filters/1.txt
> 2019/02/08 13:28:07 Writing YAML file: /opt/AdGuardHome/data/AdGuardHome.yaml
> 2019/02/08 13:28:07 Writing YAML file: /opt/AdGuardHome/data/AdGuardHome.yaml
> 2019/02/08 13:28:07 Creating dnsfilter
> 2019/02/08 13:28:07 Loading stats from querylog
> 2019/02/08 13:28:07 Starting the DNS proxy server
> 2019/02/08 13:28:07 Ratelimit is enabled and set to 20 rps
> 2019/02/08 13:28:07 The server is configured to refuse ANY requests
> 2019/02/08 13:28:07 DNS cache is enabled
> 2019/02/08 13:28:07 Creating the UDP server socket
> 2019/02/08 13:28:07 Listening to udp://[::]:53
> 2019/02/08 13:28:07 Creating the TCP server socket
> 2019/02/08 13:28:07 Listening to tcp://[::]:53
> 2019/02/08 13:28:07 Go to http://127.0.0.1:37043
> 2019/02/08 13:28:07 Entering the UDP listener loop on [::]:53
> 2019/02/08 13:28:07 Entering the TCP listener loop on [::]:53
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)

**Comment by frenck** [comment] 2019-02-08 13:58
aarch64 has issues on multiple levels (hence it is not encouraged to use yet).
Thanks for reporting this in though. All add-ons using HA authentication have this issue, which is caused by an upstream issue in LUA.

I'm awaiting updates/fixes, since there is no workaround for me available.

**Comment by frenck** [comment] 2019-04-13 17:15
@kreisklasse We had a major upgrade on the add-on. Maybe give it another shot?
I do not own such a device myself, so it is hard for me to test.

**Comment by kreisklasse** [comment] 2019-04-14 08:16
@frenck , thanks for the heads-up.
I tried i but it seems not to work, it shows the old error from above
_PANIC: unprotected error in call to Lua API (bad light userdata pointer)_
this time only once, then stops working.
see log below:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: AdGuard Home
 Network-wide ads & trackers blocking DNS server
-----------------------------------------------------------
 Add-on version: 1.0.0
 You are running the latest version of this add-on.
 System: HassOS 2.11  (aarch64 / odroid-c2)
 Home Assistant version: 0.91.3
 Supervisor version: 159
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] adguard.sh: executing... 
[cont-init.d] adguard.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:07:19] INFO: Starting AdGuard Home server...
2019/04/14 10:07:19 [info] AdGuard Home, version v0.94
2019/04/14 10:07:19 [info] main.upgradeSchema0to1(): called
2019/04/14 10:07:19 [info] main.upgradeSchema1to2(): called
2019/04/14 10:07:19 [info] main.upgradeSchema2to3(): called
2019/04/14 10:07:19 [info] Upstream 0: https://dns.cloudflare.com:443/dns-query
2019/04/14 10:07:19 [info] Start DNS server periodic jobs
2019/04/14 10:07:19 [info] Starting the DNS proxy server
2019/04/14 10:07:19 [info] Ratelimit is enabled and set to 20 rps
2019/04/14 10:07:19 [info] The server is configured to refuse ANY requests
2019/04/14 10:07:19 [info] DNS cache is enabled
2019/04/14 10:07:19 [info] Creating the UDP server socket
2019/04/14 10:07:19 [info] Listening to udp://[::]:53
2019/04/14 10:07:19 [info] Creating the TCP server socket
2019/04/14 10:07:19 [info] Listening to tcp://[::]:53
2019/04/14 10:07:19 [info] Entering the UDP listener loop on [::]:53
2019/04/14 10:07:19 [info] Entering the tcp listener loop on [::]:53
2019/04/14 10:07:19 [info] Go to http://127.0.0.1:45158
[10:07:19] INFO: Starting NGinx...
2019/04/14 10:07:19 [info] Filter 1 has been updated: 529730 bytes, 27576 rules
2019/04/14 10:07:19 [info] Saving filter 1 contents to: /opt/AdGuardHome/data/filters/1.txt
2019/04/14 10:07:19 [info] Updated filter #1.  Rules: 0 -> 27576
2019/04/14 10:07:19 [info] Upstream 0: https://dns.cloudflare.com:443/dns-query
2019/04/14 10:07:19 [info] Start reconfiguring the server
2019/04/14 10:07:19 [info] Stopping the DNS proxy server
2019/04/14 10:07:19 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2019/04/14 10:07:19 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2019/04/14 10:07:19 [info] Stopped the DNS proxy server
2019/04/14 10:07:20 [info] Starting the DNS proxy server
2019/04/14 10:07:20 [info] Ratelimit is enabled and set to 20 rps
2019/04/14 10:07:20 [info] The server is configured to refuse ANY requests
2019/04/14 10:07:20 [info] DNS cache is enabled
2019/04/14 10:07:20 [info] Creating the UDP server socket
2019/04/14 10:07:20 [info] Listening to udp://[::]:53
2019/04/14 10:07:20 [info] Creating the TCP server socket
2019/04/14 10:07:20 [info] Listening to tcp://[::]:53
2019/04/14 10:07:20 [info] Entering the tcp listener loop on [::]:53
2019/04/14 10:07:20 [info] Entering the UDP listener loop on [::]:53
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
2019/04/14 10:07:20 [info] Stopping AdGuard Home
2019/04/14 10:07:20 [info] Stopping the DNS proxy server
2019/04/14 10:07:20 [info] tcpListen.Accept() returned because we're reading from a closed connection, exiting loop
2019/04/14 10:07:20 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
2019/04/14 10:07:20 [info] Stopped the DNS proxy server
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by frenck** [comment] 2019-05-10 10:27
This issue is expected to be resolved in the next release.

**Closed** 2019-06-23 22:28 UTC
