### ISSUE TITLE
Adguard Home 4.7.2 fails to start

### ISSUE THREAD

**Issue by Milzor** [hassio-addons/addon-adguard-home#336] opened 2022-08-17 18:56 UTC
# Problem/Motivation

Fresh install of adguard home fails to start

## Expected behavior

Start the addon and be able to access the ui

## Actual behavior

During boot the following logs appear and unable to access ui

```
[20:53:37] INFO: Starting AdGuard Home server...
2022/08/17 20:53:37.435570 [info] AdGuard Home, version v0.107.10
2022/08/17 20:53:37.436795 [info] home.upgradeSchema0to1(): called
2022/08/17 20:53:37.436831 [info] deleting /data/adguard/dnsfilter.txt as we don't need it anymore
2022/08/17 20:53:37.436926 [info] home.upgradeSchema1to2(): called
2022/08/17 20:53:37.436944 [info] deleting /data/adguard/Corefile as we don't need it anymore
2022/08/17 20:53:37.436988 [info] home.upgradeSchema2to3(): called
2022/08/17 20:53:37.437013 [fatal] dns configuration is not a map
[20:53:38] INFO: Starting AdGuard Home server...
2022/08/17 20:53:38.434463 [info] AdGuard Home, version v0.107.10
2022/08/17 20:53:38.435185 [info] home.upgradeSchema0to1(): called
2022/08/17 20:53:38.435231 [info] deleting /data/adguard/dnsfilter.txt as we don't need it anymore
2022/08/17 20:53:38.435371 [info] home.upgradeSchema1to2(): called
2022/08/17 20:53:38.435391 [info] deleting /data/adguard/Corefile as we don't need it anymore
2022/08/17 20:53:38.435456 [info] home.upgradeSchema2to3(): called
2022/08/17 20:53:38.435510 [fatal] dns configuration is not a map
```

## Steps to reproduce
1. Install addon version 4.7.2 on rpi 4 
2. Start addon

**Comment by stdevel** [comment] 2022-08-18 07:11
Hi,
I have exactly the same behavior - also on a RPi 4.

**Comment by ralpho1337** [comment] 2022-08-18 07:24
Hi guys, same problem here...

**Comment by stdevel** [comment] 2022-08-18 07:25
Is there any way to downgrade the addon? Sorry if this is a dumb question, I'm quite new to home assistant and couldn't find any information about downgrading addons - also can't find the addon files on the filesystem.

**Comment by HendrikZe** [comment] 2022-08-18 16:16
Having the Same issue

**Comment by AlecRust** [comment] 2022-08-18 16:32
> Is there any way to downgrade the addon?

By default a backup is taken of the addon before an update occurs. Look in `Settings > System > Backups`.

**Comment by silvannn** [comment] 2022-08-18 16:33
The same issue

**Comment by AlecRust** [comment] 2022-08-18 16:45
Looks like an upstream issue https://github.com/AdguardTeam/AdGuardHome/issues/4846

**Comment by storkpkp** [comment] 2022-08-18 17:20
I am having the same issue as well. I notice the solution is to install the edge release of AdGuard 1.08, but I do not see how to do that. Even the edge version of the repository here has 1.07 and give the same error.

**Comment by aug70** [comment] 2022-08-19 05:48
Same

**Comment by thomas21111** [comment] 2022-08-19 06:34
Same here, edge repository does not solve issue.

**Comment by nibako** [comment] 2022-08-19 08:44
Same Problem here....

**Comment by AlecRust** [comment] 2022-08-19 09:13
Not really following all the "same here". What do you expect to be done here exactly? This is an upstream issue.

> Even the edge version of the repository here has 1.07 and give the same error.

This add-on (even "edge" versions) only use stable versions of AdGuard Home afaik.

This issue looks fixed only on AdGuard Home v0.108 which is not a stable release. Feel free to install that manually!

As for this add-on, I imagine it will be updated upon the next stable release of AdGuard Home.

In the meantime, restore your backups of this add-on prior to v4.7.2 if that's when it started breaking for you. I recommend _not_ having auto-updates enabled for this add-on.

**Comment by nibako** [comment] 2022-08-19 09:18
@AlecRust Thanks for the information. When can we expect the 0.108 release?

**Comment by stdevel** [comment] 2022-08-19 09:22
Thanks for the information @AlecRust 

> This issue looks fixed only on AdGuard Home v0.108 which is not a stable release. Feel free to install that manually!

Do you have any hints how to do this? Where are the addon binaries stored on the filesystem?

> In the meantime, restore your backups of this add-on prior to v4.7.2 if that's when it started breaking for you. I recommend _not_ having auto-updates enabled for this add-on.

That's a good hint - unfortunately I have a fresh installation so there is no backup I could restore.

**Comment by AlecRust** [comment] 2022-08-19 09:29
> When can we expect the 0.108 release?

No idea I'm not an AdGuard developer 🙂 enable release notifications on [the repository](https://github.com/AdguardTeam/AdGuardHome) to be notified.

> Do you have any hints how to do this? Where are the addon binaries stored on the filesystem?

I don't I'm afraid, I have only used AdGuard Home via this add-on. There are [getting started](https://github.com/AdguardTeam/AdGuardHome#getting-started) instructions though. Please be aware this is for building standalone AdGuard Home i.e. not as a Home Assistant add-on, which I assume you use now.

> That's a good hint - unfortunately I have a fresh installation so there is no backup I could restore.

Sadly I'm not aware of a way to install specific versions of an add-on, it would certainly be nice. Looks like there's [a feature request](https://community.home-assistant.io/t/hass-io-api-specify-version-for-add-on-install/144340) you can vote on.

**Comment by AlecRust** [comment] 2022-08-19 14:28
> Perhaps more likely is a v0.107.11 release with this fix

This has happened, and Frenck has already released a new version of this add-on.

Update and close this if the issue is resolved 👍

**Comment by frenck** [comment] 2022-08-21 10:54
Responses in other places seem that it closes this issue 👍

**Closed by frenck** 2022-08-21 10:54 UTC
